# Generated by Django 3.2.20 on 2023-08-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='user',
        ),
    ]
