# Generated by Django 3.2.20 on 2023-08-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0002_remove_refund_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='explaination',
            field=models.CharField(max_length=254),
        ),
    ]
