# Generated by Django 3.2.20 on 2023-08-07 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0003_alter_refund_explaination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='category',
        ),
    ]
