# Generated by Django 3.2.20 on 2023-08-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20230803_1901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSubscriber',
        ),
    ]
