# Generated by Django 3.2.20 on 2023-08-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Fair'), (4, '4 - Average'), (5, '5 - Good'), (6, '6 - Above Average'), (7, '7 - Very Good'), (8, '8 - Excellent'), (9, '9 - Outstanding'), (10, '10 - Perfect')], default=5),
        ),
    ]
