# Generated by Django 3.2.20 on 2023-08-06 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_userfeedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='purchase_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='today_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
