# Generated by Django 3.2.20 on 2023-08-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20230806_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfeedback',
            old_name='purchase_date',
            new_name='made_on',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='today_date',
        ),
    ]
