# Generated by Django 3.2.20 on 2023-08-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20230806_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='category',
        ),
    ]
