# Generated by Django 3.2.20 on 2023-08-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_remove_userfeedback_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='description',
            field=models.CharField(max_length=254),
        ),
    ]
