# Generated by Django 3.2.20 on 2023-08-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230809_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user_profile',
        ),
    ]
